//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 02:12:08 PM GMT 
//


package com.technobrain.trips.registration.message;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.technobrain.trips.application.message.EntityAppInputType;
import com.technobrain.trips.application.message.RevenueTypeAppInputType;
import com.technobrain.trips.core.message.AddressType;
import com.technobrain.trips.core.message.AttachmentType;
import com.technobrain.trips.core.message.BankDetailsInputType;
import com.technobrain.trips.core.message.BusinessSectorInputType;
import com.technobrain.trips.core.message.CardDetailsInputType;
import com.technobrain.trips.core.message.CommercialVehicalDetailsInputType;
import com.technobrain.trips.core.message.ContactMethodType;
import com.technobrain.trips.core.message.DocumentHeaderType;
import com.technobrain.trips.core.message.EntityAccountType;
import com.technobrain.trips.core.message.EntityClassificationType;
import com.technobrain.trips.core.message.EntityIndustryOccupationType;
import com.technobrain.trips.core.message.EntitySiteType;
import com.technobrain.trips.core.message.IdentificationType;
import com.technobrain.trips.core.message.InputType;
import com.technobrain.trips.core.message.NoteType;
import com.technobrain.trips.core.message.OrganisationType;
import com.technobrain.trips.core.message.PropertyInputType;
import com.technobrain.trips.core.message.RegimeAccountType;
import com.technobrain.trips.core.message.RelationshipType;
import com.technobrain.trips.core.message.TradingAsInputType;


/**
 * <p>Java class for OrganisationTaxpayerInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganisationTaxpayerInputType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/core/message}InputType">
 *       &lt;sequence>
 *         &lt;element name="EntityClassification" type="{http://trips.technobrain.com/core/message}EntityClassificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrganisationDetails" type="{http://trips.technobrain.com/core/message}OrganisationType" minOccurs="0"/>
 *         &lt;element name="Relationship" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Subsidiaries" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedCompanies" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Partners" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Shareholders" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://trips.technobrain.com/core/message}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attachment" type="{http://trips.technobrain.com/core/message}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Contact" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactMethod" type="{http://trips.technobrain.com/core/message}ContactMethodType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Director" type="{http://trips.technobrain.com/core/message}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DocumentHeader" type="{http://trips.technobrain.com/core/message}DocumentHeaderType" minOccurs="0"/>
 *         &lt;element name="EntityAccount" type="{http://trips.technobrain.com/core/message}EntityAccountType" minOccurs="0"/>
 *         &lt;element name="Identification" type="{http://trips.technobrain.com/core/message}IdentificationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OrganisationNotes" type="{http://trips.technobrain.com/core/message}NoteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RegimeAccount" type="{http://trips.technobrain.com/core/message}RegimeAccountType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CardDetails" type="{http://trips.technobrain.com/core/message}CardDetailsInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BankDetails" type="{http://trips.technobrain.com/core/message}BankDetailsInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UpdateReason" type="{http://trips.technobrain.com/registration/message}ReasonHistoryInputType" minOccurs="0"/>
 *         &lt;element name="Industry" type="{http://trips.technobrain.com/core/message}EntityIndustryOccupationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SiteDetails" type="{http://trips.technobrain.com/core/message}EntitySiteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Property" type="{http://trips.technobrain.com/core/message}PropertyInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EntityApplication" type="{http://trips.technobrain.com/application/message}EntityAppInputType" minOccurs="0"/>
 *         &lt;element name="RevenueTypeApplications" type="{http://trips.technobrain.com/application/message}RevenueTypeAppInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BusinessSector" type="{http://trips.technobrain.com/core/message}BusinessSectorInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TradingAsDetails" type="{http://trips.technobrain.com/core/message}TradingAsInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CommercialVehicleDetails" type="{http://trips.technobrain.com/core/message}CommercialVehicalDetailsInputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OperationSubmittedFrom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApprovalRequired" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganisationTaxpayerInputType", propOrder = {
    "entityClassification",
    "organisationDetails",
    "relationship",
    "subsidiaries",
    "relatedCompanies",
    "partners",
    "shareholders",
    "address",
    "attachment",
    "contact",
    "contactMethod",
    "director",
    "documentHeader",
    "entityAccount",
    "identification",
    "organisationNotes",
    "regimeAccount",
    "cardDetails",
    "bankDetails",
    "updateReason",
    "industry",
    "operationType",
    "siteDetails",
    "property",
    "entityApplication",
    "revenueTypeApplications",
    "businessSector",
    "tradingAsDetails",
    "commercialVehicleDetails",
    "operationSubmittedFrom",
    "approvalRequired",
    "origin"
})
public class OrganisationTaxpayerInputType
    extends InputType
{

    @XmlElement(name = "EntityClassification")
    protected List<EntityClassificationType> entityClassification;
    @XmlElement(name = "OrganisationDetails")
    protected OrganisationType organisationDetails;
    @XmlElement(name = "Relationship")
    protected List<RelationshipType> relationship;
    @XmlElement(name = "Subsidiaries")
    protected List<RelationshipType> subsidiaries;
    @XmlElement(name = "RelatedCompanies")
    protected List<RelationshipType> relatedCompanies;
    @XmlElement(name = "Partners")
    protected List<RelationshipType> partners;
    @XmlElement(name = "Shareholders")
    protected List<RelationshipType> shareholders;
    @XmlElement(name = "Address")
    protected List<AddressType> address;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "Contact")
    protected List<RelationshipType> contact;
    @XmlElement(name = "ContactMethod")
    protected List<ContactMethodType> contactMethod;
    @XmlElement(name = "Director")
    protected List<RelationshipType> director;
    @XmlElement(name = "DocumentHeader")
    protected DocumentHeaderType documentHeader;
    @XmlElement(name = "EntityAccount")
    protected EntityAccountType entityAccount;
    @XmlElement(name = "Identification")
    protected List<IdentificationType> identification;
    @XmlElement(name = "OrganisationNotes")
    protected List<NoteType> organisationNotes;
    @XmlElement(name = "RegimeAccount")
    protected List<RegimeAccountType> regimeAccount;
    @XmlElement(name = "CardDetails")
    protected List<CardDetailsInputType> cardDetails;
    @XmlElement(name = "BankDetails")
    protected List<BankDetailsInputType> bankDetails;
    @XmlElement(name = "UpdateReason")
    protected ReasonHistoryInputType updateReason;
    @XmlElement(name = "Industry")
    protected List<EntityIndustryOccupationType> industry;
    @XmlElement(name = "OperationType")
    protected String operationType;
    @XmlElement(name = "SiteDetails")
    protected List<EntitySiteType> siteDetails;
    @XmlElement(name = "Property")
    protected List<PropertyInputType> property;
    @XmlElement(name = "EntityApplication")
    protected EntityAppInputType entityApplication;
    @XmlElement(name = "RevenueTypeApplications")
    protected List<RevenueTypeAppInputType> revenueTypeApplications;
    @XmlElement(name = "BusinessSector")
    protected List<BusinessSectorInputType> businessSector;
    @XmlElement(name = "TradingAsDetails")
    protected List<TradingAsInputType> tradingAsDetails;
    @XmlElement(name = "CommercialVehicleDetails")
    protected List<CommercialVehicalDetailsInputType> commercialVehicleDetails;
    @XmlElement(name = "OperationSubmittedFrom")
    protected String operationSubmittedFrom;
    @XmlElement(name = "ApprovalRequired")
    protected Boolean approvalRequired;
    @XmlElement(name = "Origin")
    protected String origin;

    /**
     * Gets the value of the entityClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityClassificationType }
     * 
     * 
     */
    public List<EntityClassificationType> getEntityClassification() {
        if (entityClassification == null) {
            entityClassification = new ArrayList<EntityClassificationType>();
        }
        return this.entityClassification;
    }

    /**
     * Gets the value of the organisationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OrganisationType }
     *     
     */
    public OrganisationType getOrganisationDetails() {
        return organisationDetails;
    }

    /**
     * Sets the value of the organisationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganisationType }
     *     
     */
    public void setOrganisationDetails(OrganisationType value) {
        this.organisationDetails = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getRelationship() {
        if (relationship == null) {
            relationship = new ArrayList<RelationshipType>();
        }
        return this.relationship;
    }

    /**
     * Gets the value of the subsidiaries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subsidiaries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubsidiaries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getSubsidiaries() {
        if (subsidiaries == null) {
            subsidiaries = new ArrayList<RelationshipType>();
        }
        return this.subsidiaries;
    }

    /**
     * Gets the value of the relatedCompanies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedCompanies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedCompanies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getRelatedCompanies() {
        if (relatedCompanies == null) {
            relatedCompanies = new ArrayList<RelationshipType>();
        }
        return this.relatedCompanies;
    }

    /**
     * Gets the value of the partners property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partners property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartners().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getPartners() {
        if (partners == null) {
            partners = new ArrayList<RelationshipType>();
        }
        return this.partners;
    }

    /**
     * Gets the value of the shareholders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shareholders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShareholders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getShareholders() {
        if (shareholders == null) {
            shareholders = new ArrayList<RelationshipType>();
        }
        return this.shareholders;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the contact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getContact() {
        if (contact == null) {
            contact = new ArrayList<RelationshipType>();
        }
        return this.contact;
    }

    /**
     * Gets the value of the contactMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactMethodType }
     * 
     * 
     */
    public List<ContactMethodType> getContactMethod() {
        if (contactMethod == null) {
            contactMethod = new ArrayList<ContactMethodType>();
        }
        return this.contactMethod;
    }

    /**
     * Gets the value of the director property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the director property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getDirector() {
        if (director == null) {
            director = new ArrayList<RelationshipType>();
        }
        return this.director;
    }

    /**
     * Gets the value of the documentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentHeaderType }
     *     
     */
    public DocumentHeaderType getDocumentHeader() {
        return documentHeader;
    }

    /**
     * Sets the value of the documentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentHeaderType }
     *     
     */
    public void setDocumentHeader(DocumentHeaderType value) {
        this.documentHeader = value;
    }

    /**
     * Gets the value of the entityAccount property.
     * 
     * @return
     *     possible object is
     *     {@link EntityAccountType }
     *     
     */
    public EntityAccountType getEntityAccount() {
        return entityAccount;
    }

    /**
     * Sets the value of the entityAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityAccountType }
     *     
     */
    public void setEntityAccount(EntityAccountType value) {
        this.entityAccount = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getIdentification() {
        if (identification == null) {
            identification = new ArrayList<IdentificationType>();
        }
        return this.identification;
    }

    /**
     * Gets the value of the organisationNotes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organisationNotes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganisationNotes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getOrganisationNotes() {
        if (organisationNotes == null) {
            organisationNotes = new ArrayList<NoteType>();
        }
        return this.organisationNotes;
    }

    /**
     * Gets the value of the regimeAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regimeAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegimeAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RegimeAccountType }
     * 
     * 
     */
    public List<RegimeAccountType> getRegimeAccount() {
        if (regimeAccount == null) {
            regimeAccount = new ArrayList<RegimeAccountType>();
        }
        return this.regimeAccount;
    }

    /**
     * Gets the value of the cardDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardDetailsInputType }
     * 
     * 
     */
    public List<CardDetailsInputType> getCardDetails() {
        if (cardDetails == null) {
            cardDetails = new ArrayList<CardDetailsInputType>();
        }
        return this.cardDetails;
    }

    /**
     * Gets the value of the bankDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankDetailsInputType }
     * 
     * 
     */
    public List<BankDetailsInputType> getBankDetails() {
        if (bankDetails == null) {
            bankDetails = new ArrayList<BankDetailsInputType>();
        }
        return this.bankDetails;
    }

    /**
     * Gets the value of the updateReason property.
     * 
     * @return
     *     possible object is
     *     {@link ReasonHistoryInputType }
     *     
     */
    public ReasonHistoryInputType getUpdateReason() {
        return updateReason;
    }

    /**
     * Sets the value of the updateReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReasonHistoryInputType }
     *     
     */
    public void setUpdateReason(ReasonHistoryInputType value) {
        this.updateReason = value;
    }

    /**
     * Gets the value of the industry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the industry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndustry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityIndustryOccupationType }
     * 
     * 
     */
    public List<EntityIndustryOccupationType> getIndustry() {
        if (industry == null) {
            industry = new ArrayList<EntityIndustryOccupationType>();
        }
        return this.industry;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the siteDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the siteDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSiteDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntitySiteType }
     * 
     * 
     */
    public List<EntitySiteType> getSiteDetails() {
        if (siteDetails == null) {
            siteDetails = new ArrayList<EntitySiteType>();
        }
        return this.siteDetails;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyInputType }
     * 
     * 
     */
    public List<PropertyInputType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyInputType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the entityApplication property.
     * 
     * @return
     *     possible object is
     *     {@link EntityAppInputType }
     *     
     */
    public EntityAppInputType getEntityApplication() {
        return entityApplication;
    }

    /**
     * Sets the value of the entityApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityAppInputType }
     *     
     */
    public void setEntityApplication(EntityAppInputType value) {
        this.entityApplication = value;
    }

    /**
     * Gets the value of the revenueTypeApplications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the revenueTypeApplications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRevenueTypeApplications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RevenueTypeAppInputType }
     * 
     * 
     */
    public List<RevenueTypeAppInputType> getRevenueTypeApplications() {
        if (revenueTypeApplications == null) {
            revenueTypeApplications = new ArrayList<RevenueTypeAppInputType>();
        }
        return this.revenueTypeApplications;
    }

    /**
     * Gets the value of the businessSector property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businessSector property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinessSector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessSectorInputType }
     * 
     * 
     */
    public List<BusinessSectorInputType> getBusinessSector() {
        if (businessSector == null) {
            businessSector = new ArrayList<BusinessSectorInputType>();
        }
        return this.businessSector;
    }

    /**
     * Gets the value of the tradingAsDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tradingAsDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTradingAsDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TradingAsInputType }
     * 
     * 
     */
    public List<TradingAsInputType> getTradingAsDetails() {
        if (tradingAsDetails == null) {
            tradingAsDetails = new ArrayList<TradingAsInputType>();
        }
        return this.tradingAsDetails;
    }

    /**
     * Gets the value of the commercialVehicleDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commercialVehicleDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommercialVehicleDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommercialVehicalDetailsInputType }
     * 
     * 
     */
    public List<CommercialVehicalDetailsInputType> getCommercialVehicleDetails() {
        if (commercialVehicleDetails == null) {
            commercialVehicleDetails = new ArrayList<CommercialVehicalDetailsInputType>();
        }
        return this.commercialVehicleDetails;
    }

    /**
     * Gets the value of the operationSubmittedFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationSubmittedFrom() {
        return operationSubmittedFrom;
    }

    /**
     * Sets the value of the operationSubmittedFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationSubmittedFrom(String value) {
        this.operationSubmittedFrom = value;
    }

    /**
     * Gets the value of the approvalRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApprovalRequired() {
        return approvalRequired;
    }

    /**
     * Sets the value of the approvalRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApprovalRequired(Boolean value) {
        this.approvalRequired = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

}
