//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:18 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://trips.technobrain.com/interfaces/basetypes/message", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.technobrain.trips.interfaces.basetypes.message;
