//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:18 PM GMT 
//


package com.technobrain.trips.interfaces.basetypes.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeriodStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PeriodStatusType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Created"/&gt;
 *     &lt;enumeration value="Lodged"/&gt;
 *     &lt;enumeration value="Filed"/&gt;
 *     &lt;enumeration value="Paid"/&gt;
 *     &lt;enumeration value="Closed"/&gt;
 *     &lt;enumeration value="Non-Pay Actioned"/&gt;
 *     &lt;enumeration value="Non-File Actioned"/&gt;
 *     &lt;enumeration value="Partially_Paid"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PeriodStatusType")
@XmlEnum
public enum PeriodStatusType {

    @XmlEnumValue("Created")
    CREATED("Created"),
    @XmlEnumValue("Lodged")
    LODGED("Lodged"),
    @XmlEnumValue("Filed")
    FILED("Filed"),
    @XmlEnumValue("Paid")
    PAID("Paid"),
    @XmlEnumValue("Closed")
    CLOSED("Closed"),
    @XmlEnumValue("Non-Pay Actioned")
    NON_PAY_ACTIONED("Non-Pay Actioned"),
    @XmlEnumValue("Non-File Actioned")
    NON_FILE_ACTIONED("Non-File Actioned"),
    @XmlEnumValue("Partially_Paid")
    PARTIALLY_PAID("Partially_Paid");
    private final String value;

    PeriodStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PeriodStatusType fromValue(String v) {
        for (PeriodStatusType c: PeriodStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
