//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.core.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.technobrain.trips.core.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SystemMessage_QNAME = new QName("http://trips.technobrain.com/core/message", "SystemMessage");
    private final static QName _RelationshipType_QNAME = new QName("http://trips.technobrain.com/core/message", "RelationshipType");
    private final static QName _BankDetailsInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "BankDetailsInputType");
    private final static QName _SubmissionOutputType_QNAME = new QName("http://trips.technobrain.com/core/message", "SubmissionOutputType");
    private final static QName _AdditionalField_QNAME = new QName("http://trips.technobrain.com/core/message", "AdditionalField");
    private final static QName _EntityClassificationType_QNAME = new QName("http://trips.technobrain.com/core/message", "EntityClassificationType");
    private final static QName _DocumentHeaderType_QNAME = new QName("http://trips.technobrain.com/core/message", "DocumentHeaderType");
    private final static QName _EntitySiteType_QNAME = new QName("http://trips.technobrain.com/core/message", "EntitySiteType");
    private final static QName _OutputType_QNAME = new QName("http://trips.technobrain.com/core/message", "OutputType");
    private final static QName _DdocDocumentInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "DdocDocumentInputType");
    private final static QName _DDocDocumentRoleInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "DDocDocumentRoleInputType");
    private final static QName _PartnerAddInfoType_QNAME = new QName("http://trips.technobrain.com/core/message", "PartnerAddInfoType");
    private final static QName _AttachmentType_QNAME = new QName("http://trips.technobrain.com/core/message", "AttachmentType");
    private final static QName _CardDetailsInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "CardDetailsInputType");
    private final static QName _PropertyInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "PropertyInputType");
    private final static QName _RegimeAccountType_QNAME = new QName("http://trips.technobrain.com/core/message", "RegimeAccountType");
    private final static QName _CommercialVehicalDetailsInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "CommercialVehicalDetailsInputType");
    private final static QName _TradingAsInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "TradingAsInputType");
    private final static QName _OrganisationType_QNAME = new QName("http://trips.technobrain.com/core/message", "OrganisationType");
    private final static QName _BusinessSectorInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "BusinessSectorInputType");
    private final static QName _IdentificationType_QNAME = new QName("http://trips.technobrain.com/core/message", "IdentificationType");
    private final static QName _EntityIndustryOccupationType_QNAME = new QName("http://trips.technobrain.com/core/message", "EntityIndustryOccupationType");
    private final static QName _ContactMethodType_QNAME = new QName("http://trips.technobrain.com/core/message", "ContactMethodType");
    private final static QName _NoteType_QNAME = new QName("http://trips.technobrain.com/core/message", "NoteType");
    private final static QName _InputType_QNAME = new QName("http://trips.technobrain.com/core/message", "InputType");
    private final static QName _BaseType_QNAME = new QName("http://trips.technobrain.com/core/message", "BaseType");
    private final static QName _ReturnsInputType_QNAME = new QName("http://trips.technobrain.com/core/message", "ReturnsInputType");
    private final static QName _AddressType_QNAME = new QName("http://trips.technobrain.com/core/message", "AddressType");
    private final static QName _EntityAccountType_QNAME = new QName("http://trips.technobrain.com/core/message", "EntityAccountType");
    private final static QName _SystemMessageCode_QNAME = new QName("", "Code");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.technobrain.trips.core.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemMessage }
     * 
     */
    public SystemMessage createSystemMessage() {
        return new SystemMessage();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link BankDetailsInputType }
     * 
     */
    public BankDetailsInputType createBankDetailsInputType() {
        return new BankDetailsInputType();
    }

    /**
     * Create an instance of {@link SubmissionOutputType }
     * 
     */
    public SubmissionOutputType createSubmissionOutputType() {
        return new SubmissionOutputType();
    }

    /**
     * Create an instance of {@link AdditionalField }
     * 
     */
    public AdditionalField createAdditionalField() {
        return new AdditionalField();
    }

    /**
     * Create an instance of {@link EntityClassificationType }
     * 
     */
    public EntityClassificationType createEntityClassificationType() {
        return new EntityClassificationType();
    }

    /**
     * Create an instance of {@link DocumentHeaderType }
     * 
     */
    public DocumentHeaderType createDocumentHeaderType() {
        return new DocumentHeaderType();
    }

    /**
     * Create an instance of {@link EntitySiteType }
     * 
     */
    public EntitySiteType createEntitySiteType() {
        return new EntitySiteType();
    }

    /**
     * Create an instance of {@link OutputType }
     * 
     */
    public OutputType createOutputType() {
        return new OutputType();
    }

    /**
     * Create an instance of {@link DdocDocumentInputType }
     * 
     */
    public DdocDocumentInputType createDdocDocumentInputType() {
        return new DdocDocumentInputType();
    }

    /**
     * Create an instance of {@link DDocDocumentRoleInputType }
     * 
     */
    public DDocDocumentRoleInputType createDDocDocumentRoleInputType() {
        return new DDocDocumentRoleInputType();
    }

    /**
     * Create an instance of {@link PartnerAddInfoType }
     * 
     */
    public PartnerAddInfoType createPartnerAddInfoType() {
        return new PartnerAddInfoType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link CardDetailsInputType }
     * 
     */
    public CardDetailsInputType createCardDetailsInputType() {
        return new CardDetailsInputType();
    }

    /**
     * Create an instance of {@link PropertyInputType }
     * 
     */
    public PropertyInputType createPropertyInputType() {
        return new PropertyInputType();
    }

    /**
     * Create an instance of {@link RegimeAccountType }
     * 
     */
    public RegimeAccountType createRegimeAccountType() {
        return new RegimeAccountType();
    }

    /**
     * Create an instance of {@link CommercialVehicalDetailsInputType }
     * 
     */
    public CommercialVehicalDetailsInputType createCommercialVehicalDetailsInputType() {
        return new CommercialVehicalDetailsInputType();
    }

    /**
     * Create an instance of {@link TradingAsInputType }
     * 
     */
    public TradingAsInputType createTradingAsInputType() {
        return new TradingAsInputType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link BusinessSectorInputType }
     * 
     */
    public BusinessSectorInputType createBusinessSectorInputType() {
        return new BusinessSectorInputType();
    }

    /**
     * Create an instance of {@link IdentificationType }
     * 
     */
    public IdentificationType createIdentificationType() {
        return new IdentificationType();
    }

    /**
     * Create an instance of {@link EntityIndustryOccupationType }
     * 
     */
    public EntityIndustryOccupationType createEntityIndustryOccupationType() {
        return new EntityIndustryOccupationType();
    }

    /**
     * Create an instance of {@link ContactMethodType }
     * 
     */
    public ContactMethodType createContactMethodType() {
        return new ContactMethodType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link ReturnsInputType }
     * 
     */
    public ReturnsInputType createReturnsInputType() {
        return new ReturnsInputType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link EntityAccountType }
     * 
     */
    public EntityAccountType createEntityAccountType() {
        return new EntityAccountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "SystemMessage")
    public JAXBElement<SystemMessage> createSystemMessage(SystemMessage value) {
        return new JAXBElement<SystemMessage>(_SystemMessage_QNAME, SystemMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "RelationshipType")
    public JAXBElement<RelationshipType> createRelationshipType(RelationshipType value) {
        return new JAXBElement<RelationshipType>(_RelationshipType_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankDetailsInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "BankDetailsInputType")
    public JAXBElement<BankDetailsInputType> createBankDetailsInputType(BankDetailsInputType value) {
        return new JAXBElement<BankDetailsInputType>(_BankDetailsInputType_QNAME, BankDetailsInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionOutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "SubmissionOutputType")
    public JAXBElement<SubmissionOutputType> createSubmissionOutputType(SubmissionOutputType value) {
        return new JAXBElement<SubmissionOutputType>(_SubmissionOutputType_QNAME, SubmissionOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdditionalField }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "AdditionalField")
    public JAXBElement<AdditionalField> createAdditionalField(AdditionalField value) {
        return new JAXBElement<AdditionalField>(_AdditionalField_QNAME, AdditionalField.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityClassificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "EntityClassificationType")
    public JAXBElement<EntityClassificationType> createEntityClassificationType(EntityClassificationType value) {
        return new JAXBElement<EntityClassificationType>(_EntityClassificationType_QNAME, EntityClassificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "DocumentHeaderType")
    public JAXBElement<DocumentHeaderType> createDocumentHeaderType(DocumentHeaderType value) {
        return new JAXBElement<DocumentHeaderType>(_DocumentHeaderType_QNAME, DocumentHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntitySiteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "EntitySiteType")
    public JAXBElement<EntitySiteType> createEntitySiteType(EntitySiteType value) {
        return new JAXBElement<EntitySiteType>(_EntitySiteType_QNAME, EntitySiteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "OutputType")
    public JAXBElement<OutputType> createOutputType(OutputType value) {
        return new JAXBElement<OutputType>(_OutputType_QNAME, OutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DdocDocumentInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "DdocDocumentInputType")
    public JAXBElement<DdocDocumentInputType> createDdocDocumentInputType(DdocDocumentInputType value) {
        return new JAXBElement<DdocDocumentInputType>(_DdocDocumentInputType_QNAME, DdocDocumentInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DDocDocumentRoleInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "DDocDocumentRoleInputType")
    public JAXBElement<DDocDocumentRoleInputType> createDDocDocumentRoleInputType(DDocDocumentRoleInputType value) {
        return new JAXBElement<DDocDocumentRoleInputType>(_DDocDocumentRoleInputType_QNAME, DDocDocumentRoleInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartnerAddInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "PartnerAddInfoType")
    public JAXBElement<PartnerAddInfoType> createPartnerAddInfoType(PartnerAddInfoType value) {
        return new JAXBElement<PartnerAddInfoType>(_PartnerAddInfoType_QNAME, PartnerAddInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttachmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "AttachmentType")
    public JAXBElement<AttachmentType> createAttachmentType(AttachmentType value) {
        return new JAXBElement<AttachmentType>(_AttachmentType_QNAME, AttachmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CardDetailsInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "CardDetailsInputType")
    public JAXBElement<CardDetailsInputType> createCardDetailsInputType(CardDetailsInputType value) {
        return new JAXBElement<CardDetailsInputType>(_CardDetailsInputType_QNAME, CardDetailsInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "PropertyInputType")
    public JAXBElement<PropertyInputType> createPropertyInputType(PropertyInputType value) {
        return new JAXBElement<PropertyInputType>(_PropertyInputType_QNAME, PropertyInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegimeAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "RegimeAccountType")
    public JAXBElement<RegimeAccountType> createRegimeAccountType(RegimeAccountType value) {
        return new JAXBElement<RegimeAccountType>(_RegimeAccountType_QNAME, RegimeAccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommercialVehicalDetailsInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "CommercialVehicalDetailsInputType")
    public JAXBElement<CommercialVehicalDetailsInputType> createCommercialVehicalDetailsInputType(CommercialVehicalDetailsInputType value) {
        return new JAXBElement<CommercialVehicalDetailsInputType>(_CommercialVehicalDetailsInputType_QNAME, CommercialVehicalDetailsInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TradingAsInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "TradingAsInputType")
    public JAXBElement<TradingAsInputType> createTradingAsInputType(TradingAsInputType value) {
        return new JAXBElement<TradingAsInputType>(_TradingAsInputType_QNAME, TradingAsInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "OrganisationType")
    public JAXBElement<OrganisationType> createOrganisationType(OrganisationType value) {
        return new JAXBElement<OrganisationType>(_OrganisationType_QNAME, OrganisationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessSectorInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "BusinessSectorInputType")
    public JAXBElement<BusinessSectorInputType> createBusinessSectorInputType(BusinessSectorInputType value) {
        return new JAXBElement<BusinessSectorInputType>(_BusinessSectorInputType_QNAME, BusinessSectorInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "IdentificationType")
    public JAXBElement<IdentificationType> createIdentificationType(IdentificationType value) {
        return new JAXBElement<IdentificationType>(_IdentificationType_QNAME, IdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityIndustryOccupationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "EntityIndustryOccupationType")
    public JAXBElement<EntityIndustryOccupationType> createEntityIndustryOccupationType(EntityIndustryOccupationType value) {
        return new JAXBElement<EntityIndustryOccupationType>(_EntityIndustryOccupationType_QNAME, EntityIndustryOccupationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactMethodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "ContactMethodType")
    public JAXBElement<ContactMethodType> createContactMethodType(ContactMethodType value) {
        return new JAXBElement<ContactMethodType>(_ContactMethodType_QNAME, ContactMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "NoteType")
    public JAXBElement<NoteType> createNoteType(NoteType value) {
        return new JAXBElement<NoteType>(_NoteType_QNAME, NoteType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "InputType")
    public JAXBElement<InputType> createInputType(InputType value) {
        return new JAXBElement<InputType>(_InputType_QNAME, InputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "BaseType")
    public JAXBElement<BaseType> createBaseType(BaseType value) {
        return new JAXBElement<BaseType>(_BaseType_QNAME, BaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnsInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "ReturnsInputType")
    public JAXBElement<ReturnsInputType> createReturnsInputType(ReturnsInputType value) {
        return new JAXBElement<ReturnsInputType>(_ReturnsInputType_QNAME, ReturnsInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "AddressType")
    public JAXBElement<AddressType> createAddressType(AddressType value) {
        return new JAXBElement<AddressType>(_AddressType_QNAME, AddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/core/message", name = "EntityAccountType")
    public JAXBElement<EntityAccountType> createEntityAccountType(EntityAccountType value) {
        return new JAXBElement<EntityAccountType>(_EntityAccountType_QNAME, EntityAccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Code", scope = SystemMessage.class)
    public JAXBElement<String> createSystemMessageCode(String value) {
        return new JAXBElement<String>(_SystemMessageCode_QNAME, String.class, SystemMessage.class, value);
    }

}
