//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.core.message;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;


/**
 * <p>Java class for OrganisationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganisationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/core/message}InputType">
 *       &lt;sequence>
 *         &lt;element name="AccountYearEndDay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AccountYearEndMonth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="BranchFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BusinessEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="BusinessStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CompanyRegNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HQBranchIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExportIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="TaxConsultantStatusIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ImportIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LegalName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LegalNamePhonetic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LegalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiscellaneousVerification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalSalesTurnoverPA" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="PersonalTaxNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferrentialCurrency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxableTurnoverAtRegistration" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FacilityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PurposeOfTin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntentionToEmployOthersIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ExistingBusinessCapitalEquity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="ExistingBusinessCapitalLoan" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="FromRGD" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EntityStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganisationType", propOrder = {
    "accountYearEndDay",
    "accountYearEndMonth",
    "branchFlag",
    "businessEndDate",
    "businessStartDate",
    "companyRegNo",
    "companyStatus",
    "hqBranchIndicator",
    "exportIndicator",
    "taxConsultantStatusIndicator",
    "importIndicator",
    "legalName",
    "legalNamePhonetic",
    "legalStatus",
    "miscellaneousVerification",
    "totalSalesTurnoverPA",
    "personalTaxNo",
    "preferrentialCurrency",
    "taxableTurnoverAtRegistration",
    "website",
    "companyRegDate",
    "facilityType",
    "purposeOfTin",
    "intentionToEmployOthersIndicator",
    "existingBusinessCapitalEquity",
    "existingBusinessCapitalLoan",
    "fromRGD",
    "entityStatus"
})
public class OrganisationType
    extends InputType
{

    @XmlElement(name = "AccountYearEndDay")
    protected Integer accountYearEndDay;
    @XmlElement(name = "AccountYearEndMonth")
    protected Integer accountYearEndMonth;
    @XmlElement(name = "BranchFlag")
    protected String branchFlag;
    @XmlElement(name = "BusinessEndDate")
    @XmlSchemaType(name = "date")
    protected Calendar businessEndDate;
    @XmlElement(name = "BusinessStartDate")
    @XmlSchemaType(name = "date")
    protected Calendar businessStartDate;
    @XmlElement(name = "CompanyRegNo")
    protected String companyRegNo;
    @XmlElement(name = "CompanyStatus")
    protected String companyStatus;
    @XmlElement(name = "HQBranchIndicator")
    protected String hqBranchIndicator;
    @XmlElement(name = "ExportIndicator")
    protected Boolean exportIndicator;
    @XmlElement(name = "TaxConsultantStatusIndicator")
    protected Boolean taxConsultantStatusIndicator;
    @XmlElement(name = "ImportIndicator")
    protected Boolean importIndicator;
    @XmlElement(name = "LegalName")
    protected String legalName;
    @XmlElement(name = "LegalNamePhonetic")
    protected String legalNamePhonetic;
    @XmlElement(name = "LegalStatus")
    protected String legalStatus;
    @XmlElement(name = "MiscellaneousVerification")
    protected String miscellaneousVerification;
    @XmlElement(name = "TotalSalesTurnoverPA")
    protected Long totalSalesTurnoverPA;
    @XmlElement(name = "PersonalTaxNo")
    protected String personalTaxNo;
    @XmlElement(name = "PreferrentialCurrency")
    protected String preferrentialCurrency;
    @XmlElement(name = "TaxableTurnoverAtRegistration")
    protected BigDecimal taxableTurnoverAtRegistration;
    @XmlElement(name = "Website")
    protected String website;
    @XmlElement(name = "CompanyRegDate")
    @XmlSchemaType(name = "date")
    protected Calendar companyRegDate;
    @XmlElement(name = "FacilityType")
    protected String facilityType;
    @XmlElement(name = "PurposeOfTin")
    protected String purposeOfTin;
    @XmlElement(name = "IntentionToEmployOthersIndicator")
    protected Boolean intentionToEmployOthersIndicator;
    @XmlElement(name = "ExistingBusinessCapitalEquity")
    protected Long existingBusinessCapitalEquity;
    @XmlElement(name = "ExistingBusinessCapitalLoan")
    protected Long existingBusinessCapitalLoan;
    @XmlElement(name = "FromRGD")
    protected Boolean fromRGD;
    @XmlElement(name = "EntityStatus")
    protected String entityStatus;

    /**
     * Gets the value of the accountYearEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountYearEndDay() {
        return accountYearEndDay;
    }

    /**
     * Sets the value of the accountYearEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountYearEndDay(Integer value) {
        this.accountYearEndDay = value;
    }

    /**
     * Gets the value of the accountYearEndMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountYearEndMonth() {
        return accountYearEndMonth;
    }

    /**
     * Sets the value of the accountYearEndMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountYearEndMonth(Integer value) {
        this.accountYearEndMonth = value;
    }

    /**
     * Gets the value of the branchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchFlag() {
        return branchFlag;
    }

    /**
     * Sets the value of the branchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchFlag(String value) {
        this.branchFlag = value;
    }

    /**
     * Gets the value of the businessEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getBusinessEndDate() {
        return businessEndDate;
    }

    /**
     * Sets the value of the businessEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setBusinessEndDate(Calendar value) {
        this.businessEndDate = value;
    }

    /**
     * Gets the value of the businessStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getBusinessStartDate() {
        return businessStartDate;
    }

    /**
     * Sets the value of the businessStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setBusinessStartDate(Calendar value) {
        this.businessStartDate = value;
    }

    /**
     * Gets the value of the companyRegNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyRegNo() {
        return companyRegNo;
    }

    /**
     * Sets the value of the companyRegNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyRegNo(String value) {
        this.companyRegNo = value;
    }

    /**
     * Gets the value of the companyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyStatus() {
        return companyStatus;
    }

    /**
     * Sets the value of the companyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyStatus(String value) {
        this.companyStatus = value;
    }

    /**
     * Gets the value of the hqBranchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHQBranchIndicator() {
        return hqBranchIndicator;
    }

    /**
     * Sets the value of the hqBranchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHQBranchIndicator(String value) {
        this.hqBranchIndicator = value;
    }

    /**
     * Gets the value of the exportIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExportIndicator() {
        return exportIndicator;
    }

    /**
     * Sets the value of the exportIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExportIndicator(Boolean value) {
        this.exportIndicator = value;
    }

    /**
     * Gets the value of the taxConsultantStatusIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxConsultantStatusIndicator() {
        return taxConsultantStatusIndicator;
    }

    /**
     * Sets the value of the taxConsultantStatusIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxConsultantStatusIndicator(Boolean value) {
        this.taxConsultantStatusIndicator = value;
    }

    /**
     * Gets the value of the importIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImportIndicator() {
        return importIndicator;
    }

    /**
     * Sets the value of the importIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImportIndicator(Boolean value) {
        this.importIndicator = value;
    }

    /**
     * Gets the value of the legalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * Sets the value of the legalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalName(String value) {
        this.legalName = value;
    }

    /**
     * Gets the value of the legalNamePhonetic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalNamePhonetic() {
        return legalNamePhonetic;
    }

    /**
     * Sets the value of the legalNamePhonetic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalNamePhonetic(String value) {
        this.legalNamePhonetic = value;
    }

    /**
     * Gets the value of the legalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the miscellaneousVerification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiscellaneousVerification() {
        return miscellaneousVerification;
    }

    /**
     * Sets the value of the miscellaneousVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiscellaneousVerification(String value) {
        this.miscellaneousVerification = value;
    }

    /**
     * Gets the value of the totalSalesTurnoverPA property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalSalesTurnoverPA() {
        return totalSalesTurnoverPA;
    }

    /**
     * Sets the value of the totalSalesTurnoverPA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalSalesTurnoverPA(Long value) {
        this.totalSalesTurnoverPA = value;
    }

    /**
     * Gets the value of the personalTaxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalTaxNo() {
        return personalTaxNo;
    }

    /**
     * Sets the value of the personalTaxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalTaxNo(String value) {
        this.personalTaxNo = value;
    }

    /**
     * Gets the value of the preferrentialCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferrentialCurrency() {
        return preferrentialCurrency;
    }

    /**
     * Sets the value of the preferrentialCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferrentialCurrency(String value) {
        this.preferrentialCurrency = value;
    }

    /**
     * Gets the value of the taxableTurnoverAtRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxableTurnoverAtRegistration() {
        return taxableTurnoverAtRegistration;
    }

    /**
     * Sets the value of the taxableTurnoverAtRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxableTurnoverAtRegistration(BigDecimal value) {
        this.taxableTurnoverAtRegistration = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the companyRegDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getCompanyRegDate() {
        return companyRegDate;
    }

    /**
     * Sets the value of the companyRegDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setCompanyRegDate(Calendar value) {
        this.companyRegDate = value;
    }

    /**
     * Gets the value of the facilityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * Sets the value of the facilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityType(String value) {
        this.facilityType = value;
    }

    /**
     * Gets the value of the purposeOfTin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurposeOfTin() {
        return purposeOfTin;
    }

    /**
     * Sets the value of the purposeOfTin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurposeOfTin(String value) {
        this.purposeOfTin = value;
    }

    /**
     * Gets the value of the intentionToEmployOthersIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntentionToEmployOthersIndicator() {
        return intentionToEmployOthersIndicator;
    }

    /**
     * Sets the value of the intentionToEmployOthersIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntentionToEmployOthersIndicator(Boolean value) {
        this.intentionToEmployOthersIndicator = value;
    }

    /**
     * Gets the value of the existingBusinessCapitalEquity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExistingBusinessCapitalEquity() {
        return existingBusinessCapitalEquity;
    }

    /**
     * Sets the value of the existingBusinessCapitalEquity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExistingBusinessCapitalEquity(Long value) {
        this.existingBusinessCapitalEquity = value;
    }

    /**
     * Gets the value of the existingBusinessCapitalLoan property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExistingBusinessCapitalLoan() {
        return existingBusinessCapitalLoan;
    }

    /**
     * Sets the value of the existingBusinessCapitalLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExistingBusinessCapitalLoan(Long value) {
        this.existingBusinessCapitalLoan = value;
    }

    /**
     * Gets the value of the fromRGD property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFromRGD() {
        return fromRGD;
    }

    /**
     * Sets the value of the fromRGD property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFromRGD(Boolean value) {
        this.fromRGD = value;
    }

    /**
     * Gets the value of the entityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityStatus() {
        return entityStatus;
    }

    /**
     * Sets the value of the entityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityStatus(String value) {
        this.entityStatus = value;
    }

}
