//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.core.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;


/**
 * <p>Java class for RelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelationshipType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/core/message}InputType">
 *       &lt;sequence>
 *         &lt;element name="RelationshipEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RelationshipStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RelationshipTargetID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RelationshipType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TargetEntityName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RelationshipStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TargetEntityType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DirectorsName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdditionalInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployerTIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployersName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmploymentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartnerAddInfoType" type="{http://trips.technobrain.com/core/message}PartnerAddInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationshipType", propOrder = {
    "relationshipEndDate",
    "relationshipStartDate",
    "relationshipTargetID",
    "relationshipType",
    "targetEntityName",
    "relationshipStatus",
    "targetEntityType",
    "primaryIndicator",
    "directorsName",
    "nationality",
    "address",
    "contactDetails",
    "additionalInformation",
    "otherInfo",
    "employerTIN",
    "employersName",
    "employmentType",
    "partnerAddInfoType"
})
public class RelationshipType
    extends InputType
{

    @XmlElement(name = "RelationshipEndDate")
    @XmlSchemaType(name = "date")
    protected Calendar relationshipEndDate;
    @XmlElement(name = "RelationshipStartDate")
    @XmlSchemaType(name = "date")
    protected Calendar relationshipStartDate;
    @XmlElement(name = "RelationshipTargetID")
    protected Long relationshipTargetID;
    @XmlElement(name = "RelationshipType")
    protected String relationshipType;
    @XmlElement(name = "TargetEntityName")
    protected String targetEntityName;
    @XmlElement(name = "RelationshipStatus")
    protected String relationshipStatus;
    @XmlElement(name = "TargetEntityType")
    protected String targetEntityType;
    @XmlElement(name = "PrimaryIndicator")
    protected Boolean primaryIndicator;
    @XmlElement(name = "DirectorsName")
    protected String directorsName;
    @XmlElement(name = "Nationality")
    protected String nationality;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "ContactDetails")
    protected String contactDetails;
    @XmlElement(name = "AdditionalInformation")
    protected String additionalInformation;
    @XmlElement(name = "OtherInfo")
    protected String otherInfo;
    @XmlElement(name = "EmployerTIN")
    protected String employerTIN;
    @XmlElement(name = "EmployersName")
    protected String employersName;
    @XmlElement(name = "EmploymentType")
    protected String employmentType;
    @XmlElement(name = "PartnerAddInfoType")
    protected PartnerAddInfoType partnerAddInfoType;

    /**
     * Gets the value of the relationshipEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getRelationshipEndDate() {
        return relationshipEndDate;
    }

    /**
     * Sets the value of the relationshipEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setRelationshipEndDate(Calendar value) {
        this.relationshipEndDate = value;
    }

    /**
     * Gets the value of the relationshipStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getRelationshipStartDate() {
        return relationshipStartDate;
    }

    /**
     * Sets the value of the relationshipStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setRelationshipStartDate(Calendar value) {
        this.relationshipStartDate = value;
    }

    /**
     * Gets the value of the relationshipTargetID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRelationshipTargetID() {
        return relationshipTargetID;
    }

    /**
     * Sets the value of the relationshipTargetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRelationshipTargetID(Long value) {
        this.relationshipTargetID = value;
    }

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipType(String value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the targetEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntityName() {
        return targetEntityName;
    }

    /**
     * Sets the value of the targetEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntityName(String value) {
        this.targetEntityName = value;
    }

    /**
     * Gets the value of the relationshipStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipStatus() {
        return relationshipStatus;
    }

    /**
     * Sets the value of the relationshipStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipStatus(String value) {
        this.relationshipStatus = value;
    }

    /**
     * Gets the value of the targetEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntityType() {
        return targetEntityType;
    }

    /**
     * Sets the value of the targetEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntityType(String value) {
        this.targetEntityType = value;
    }

    /**
     * Gets the value of the primaryIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimaryIndicator() {
        return primaryIndicator;
    }

    /**
     * Sets the value of the primaryIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimaryIndicator(Boolean value) {
        this.primaryIndicator = value;
    }

    /**
     * Gets the value of the directorsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorsName() {
        return directorsName;
    }

    /**
     * Sets the value of the directorsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorsName(String value) {
        this.directorsName = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactDetails(String value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInformation(String value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the otherInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherInfo() {
        return otherInfo;
    }

    /**
     * Sets the value of the otherInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherInfo(String value) {
        this.otherInfo = value;
    }

    /**
     * Gets the value of the employerTIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployerTIN() {
        return employerTIN;
    }

    /**
     * Sets the value of the employerTIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployerTIN(String value) {
        this.employerTIN = value;
    }

    /**
     * Gets the value of the employersName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployersName() {
        return employersName;
    }

    /**
     * Sets the value of the employersName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployersName(String value) {
        this.employersName = value;
    }

    /**
     * Gets the value of the employmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * Sets the value of the employmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentType(String value) {
        this.employmentType = value;
    }

    /**
     * Gets the value of the partnerAddInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link PartnerAddInfoType }
     *     
     */
    public PartnerAddInfoType getPartnerAddInfoType() {
        return partnerAddInfoType;
    }

    /**
     * Sets the value of the partnerAddInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartnerAddInfoType }
     *     
     */
    public void setPartnerAddInfoType(PartnerAddInfoType value) {
        this.partnerAddInfoType = value;
    }

}
