//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.application.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;
import com.technobrain.trips.core.message.InputType;


/**
 * <p>Java class for ApplicationAuthorisationInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationAuthorisationInputType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/core/message}InputType">
 *       &lt;sequence>
 *         &lt;element name="AuthDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AuthEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AuthExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AuthReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuthStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationAuthorisationInputType", propOrder = {
    "authDate",
    "authEffectiveDate",
    "authExpiryDate",
    "authReference",
    "authStatus"
})
public class ApplicationAuthorisationInputType
    extends InputType
{

    @XmlElement(name = "AuthDate")
    @XmlSchemaType(name = "date")
    protected Calendar authDate;
    @XmlElement(name = "AuthEffectiveDate")
    @XmlSchemaType(name = "date")
    protected Calendar authEffectiveDate;
    @XmlElement(name = "AuthExpiryDate")
    @XmlSchemaType(name = "date")
    protected Calendar authExpiryDate;
    @XmlElement(name = "AuthReference")
    protected String authReference;
    @XmlElement(name = "AuthStatus")
    protected String authStatus;

    /**
     * Gets the value of the authDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getAuthDate() {
        return authDate;
    }

    /**
     * Sets the value of the authDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setAuthDate(Calendar value) {
        this.authDate = value;
    }

    /**
     * Gets the value of the authEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getAuthEffectiveDate() {
        return authEffectiveDate;
    }

    /**
     * Sets the value of the authEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setAuthEffectiveDate(Calendar value) {
        this.authEffectiveDate = value;
    }

    /**
     * Gets the value of the authExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getAuthExpiryDate() {
        return authExpiryDate;
    }

    /**
     * Sets the value of the authExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setAuthExpiryDate(Calendar value) {
        this.authExpiryDate = value;
    }

    /**
     * Gets the value of the authReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthReference() {
        return authReference;
    }

    /**
     * Sets the value of the authReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthReference(String value) {
        this.authReference = value;
    }

    /**
     * Gets the value of the authStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthStatus() {
        return authStatus;
    }

    /**
     * Sets the value of the authStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthStatus(String value) {
        this.authStatus = value;
    }

}
