//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.application.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.technobrain.trips.application.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RevenueTypeAppInputType_QNAME = new QName("http://trips.technobrain.com/application/message", "RevenueTypeAppInputType");
    private final static QName _ApplicationInputType_QNAME = new QName("http://trips.technobrain.com/application/message", "ApplicationInputType");
    private final static QName _EntityAppInputType_QNAME = new QName("http://trips.technobrain.com/application/message", "EntityAppInputType");
    private final static QName _ApplicationAuthorisationInputType_QNAME = new QName("http://trips.technobrain.com/application/message", "ApplicationAuthorisationInputType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.technobrain.trips.application.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RevenueTypeAppInputType }
     * 
     */
    public RevenueTypeAppInputType createRevenueTypeAppInputType() {
        return new RevenueTypeAppInputType();
    }

    /**
     * Create an instance of {@link ApplicationAuthorisationInputType }
     * 
     */
    public ApplicationAuthorisationInputType createApplicationAuthorisationInputType() {
        return new ApplicationAuthorisationInputType();
    }

    /**
     * Create an instance of {@link EntityAppInputType }
     * 
     */
    public EntityAppInputType createEntityAppInputType() {
        return new EntityAppInputType();
    }

    /**
     * Create an instance of {@link ApplicationInputType }
     * 
     */
    public ApplicationInputType createApplicationInputType() {
        return new ApplicationInputType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevenueTypeAppInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/application/message", name = "RevenueTypeAppInputType")
    public JAXBElement<RevenueTypeAppInputType> createRevenueTypeAppInputType(RevenueTypeAppInputType value) {
        return new JAXBElement<RevenueTypeAppInputType>(_RevenueTypeAppInputType_QNAME, RevenueTypeAppInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/application/message", name = "ApplicationInputType")
    public JAXBElement<ApplicationInputType> createApplicationInputType(ApplicationInputType value) {
        return new JAXBElement<ApplicationInputType>(_ApplicationInputType_QNAME, ApplicationInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityAppInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/application/message", name = "EntityAppInputType")
    public JAXBElement<EntityAppInputType> createEntityAppInputType(EntityAppInputType value) {
        return new JAXBElement<EntityAppInputType>(_EntityAppInputType_QNAME, EntityAppInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationAuthorisationInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/application/message", name = "ApplicationAuthorisationInputType")
    public JAXBElement<ApplicationAuthorisationInputType> createApplicationAuthorisationInputType(ApplicationAuthorisationInputType value) {
        return new JAXBElement<ApplicationAuthorisationInputType>(_ApplicationAuthorisationInputType_QNAME, ApplicationAuthorisationInputType.class, null, value);
    }

}
