//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 02:38:30 PM GMT 
//


package com.technobrain.trips.application.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RevenueTypeAppInputType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RevenueTypeAppInputType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/application/message}ApplicationInputType">
 *       &lt;sequence>
 *         &lt;element name="RevenueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoRefundInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="RefundInhibitInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevenueTypeAppInputType", propOrder = {
    "revenueType",
    "autoRefundInd",
    "refundInhibitInd"
})
public class RevenueTypeAppInputType
    extends ApplicationInputType
{

    @XmlElement(name = "RevenueType")
    protected String revenueType;
    @XmlElement(name = "AutoRefundInd")
    protected Boolean autoRefundInd;
    @XmlElement(name = "RefundInhibitInd")
    protected Boolean refundInhibitInd;

    /**
     * Gets the value of the revenueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueType() {
        return revenueType;
    }

    /**
     * Sets the value of the revenueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueType(String value) {
        this.revenueType = value;
    }

    /**
     * Gets the value of the autoRefundInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutoRefundInd() {
        return autoRefundInd;
    }

    /**
     * Sets the value of the autoRefundInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoRefundInd(Boolean value) {
        this.autoRefundInd = value;
    }

    /**
     * Gets the value of the refundInhibitInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefundInhibitInd() {
        return refundInhibitInd;
    }

    /**
     * Sets the value of the refundInhibitInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefundInhibitInd(Boolean value) {
        this.refundInhibitInd = value;
    }

}
