//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.01 at 11:40:08 AM GMT 
//


package com.technobrain.trips.interfaces.systemtypes.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;


/**
 * <p>Java class for ReferenceDataRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceDataRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TableName" type="{http://trips.technobrain.com/interfaces/systemtypes/message}RefTableNameType"/&gt;
 *         &lt;element name="UpdatedSince" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Category" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceDataRequest", propOrder = {
    "tableName",
    "updatedSince",
    "category"
})
public class ReferenceDataRequest {

    @XmlElement(name = "TableName", required = true)
    @XmlSchemaType(name = "string")
    protected RefTableNameType tableName;
    @XmlElement(name = "UpdatedSince", required = true)
    @XmlSchemaType(name = "date")
    protected Calendar updatedSince;
    @XmlElement(name = "Category", required = true)
    protected String category;

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link RefTableNameType }
     *     
     */
    public RefTableNameType getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefTableNameType }
     *     
     */
    public void setTableName(RefTableNameType value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the updatedSince property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getUpdatedSince() {
        return updatedSince;
    }

    /**
     * Sets the value of the updatedSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setUpdatedSince(Calendar value) {
        this.updatedSince = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
