//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.01 at 11:40:08 AM GMT 
//


package com.technobrain.trips.interfaces.systemtypes.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RefTableNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RefTableNameType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Title"/&gt;
 *     &lt;enumeration value="Country"/&gt;
 *     &lt;enumeration value="Region"/&gt;
 *     &lt;enumeration value="District"/&gt;
 *     &lt;enumeration value="BusinessSector"/&gt;
 *     &lt;enumeration value="Bank"/&gt;
 *     &lt;enumeration value="BankBranch"/&gt;
 *     &lt;enumeration value="DocumentType"/&gt;
 *     &lt;enumeration value="DocumentStatus"/&gt;
 *     &lt;enumeration value="TransactionType"/&gt;
 *     &lt;enumeration value="VehicleType"/&gt;
 *     &lt;enumeration value="DocumentEvent"/&gt;
 *     &lt;enumeration value="Occupation"/&gt;
 *     &lt;enumeration value="OccupationCategory"/&gt;
 *     &lt;enumeration value="AccountStatus"/&gt;
 *     &lt;enumeration value="TaxHoliday"/&gt;
 *     &lt;enumeration value="Currency"/&gt;
 *     &lt;enumeration value="ReturnType"/&gt;
 *     &lt;enumeration value="Status"/&gt;
 *     &lt;enumeration value="Relationship"/&gt;
 *     &lt;enumeration value="Office"/&gt;
 *     &lt;enumeration value="LegalStatusType"/&gt;
 *     &lt;enumeration value="EvtType"/&gt;
 *     &lt;enumeration value="MonthOfYear"/&gt;
 *     &lt;enumeration value="DocTypeRetTypeRel"/&gt;
 *     &lt;enumeration value="AccountingMethod"/&gt;
 *     &lt;enumeration value="AssetType"/&gt;
 *     &lt;enumeration value="BusinessLocation"/&gt;
 *     &lt;enumeration value="Commodity"/&gt;
 *     &lt;enumeration value="CostType"/&gt;
 *     &lt;enumeration value="GiftType"/&gt;
 *     &lt;enumeration value="Locations"/&gt;
 *     &lt;enumeration value="MeasurementUnits"/&gt;
 *     &lt;enumeration value="MineralType"/&gt;
 *     &lt;enumeration value="OwnershipType"/&gt;
 *     &lt;enumeration value="PAYEPosition"/&gt;
 *     &lt;enumeration value="ProductType"/&gt;
 *     &lt;enumeration value="PropertyType"/&gt;
 *     &lt;enumeration value="PropertyUse"/&gt;
 *     &lt;enumeration value="Service"/&gt;
 *     &lt;enumeration value="WithholdingType"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RefTableNameType")
@XmlEnum
public enum RefTableNameType {

    @XmlEnumValue("Title")
    TITLE("Title"),
    @XmlEnumValue("Country")
    COUNTRY("Country"),
    @XmlEnumValue("Region")
    REGION("Region"),
    @XmlEnumValue("District")
    DISTRICT("District"),
    @XmlEnumValue("BusinessSector")
    BUSINESS_SECTOR("BusinessSector"),
    @XmlEnumValue("Bank")
    BANK("Bank"),
    @XmlEnumValue("BankBranch")
    BANK_BRANCH("BankBranch"),
    @XmlEnumValue("DocumentType")
    DOCUMENT_TYPE("DocumentType"),
    @XmlEnumValue("DocumentStatus")
    DOCUMENT_STATUS("DocumentStatus"),
    @XmlEnumValue("TransactionType")
    TRANSACTION_TYPE("TransactionType"),
    @XmlEnumValue("VehicleType")
    VEHICLE_TYPE("VehicleType"),
    @XmlEnumValue("DocumentEvent")
    DOCUMENT_EVENT("DocumentEvent"),
    @XmlEnumValue("Occupation")
    OCCUPATION("Occupation"),
    @XmlEnumValue("OccupationCategory")
    OCCUPATION_CATEGORY("OccupationCategory"),
    @XmlEnumValue("AccountStatus")
    ACCOUNT_STATUS("AccountStatus"),
    @XmlEnumValue("TaxHoliday")
    TAX_HOLIDAY("TaxHoliday"),
    @XmlEnumValue("Currency")
    CURRENCY("Currency"),
    @XmlEnumValue("ReturnType")
    RETURN_TYPE("ReturnType"),
    @XmlEnumValue("Status")
    STATUS("Status"),
    @XmlEnumValue("Relationship")
    RELATIONSHIP("Relationship"),
    @XmlEnumValue("Office")
    OFFICE("Office"),
    @XmlEnumValue("LegalStatusType")
    LEGAL_STATUS_TYPE("LegalStatusType"),
    @XmlEnumValue("EvtType")
    EVT_TYPE("EvtType"),
    @XmlEnumValue("MonthOfYear")
    MONTH_OF_YEAR("MonthOfYear"),
    @XmlEnumValue("DocTypeRetTypeRel")
    DOC_TYPE_RET_TYPE_REL("DocTypeRetTypeRel"),
    @XmlEnumValue("AccountingMethod")
    ACCOUNTING_METHOD("AccountingMethod"),
    @XmlEnumValue("AssetType")
    ASSET_TYPE("AssetType"),
    @XmlEnumValue("BusinessLocation")
    BUSINESS_LOCATION("BusinessLocation"),
    @XmlEnumValue("Commodity")
    COMMODITY("Commodity"),
    @XmlEnumValue("CostType")
    COST_TYPE("CostType"),
    @XmlEnumValue("GiftType")
    GIFT_TYPE("GiftType"),
    @XmlEnumValue("Locations")
    LOCATIONS("Locations"),
    @XmlEnumValue("MeasurementUnits")
    MEASUREMENT_UNITS("MeasurementUnits"),
    @XmlEnumValue("MineralType")
    MINERAL_TYPE("MineralType"),
    @XmlEnumValue("OwnershipType")
    OWNERSHIP_TYPE("OwnershipType"),
    @XmlEnumValue("PAYEPosition")
    PAYE_POSITION("PAYEPosition"),
    @XmlEnumValue("ProductType")
    PRODUCT_TYPE("ProductType"),
    @XmlEnumValue("PropertyType")
    PROPERTY_TYPE("PropertyType"),
    @XmlEnumValue("PropertyUse")
    PROPERTY_USE("PropertyUse"),
    @XmlEnumValue("Service")
    SERVICE("Service"),
    @XmlEnumValue("WithholdingType")
    WITHHOLDING_TYPE("WithholdingType");
    private final String value;

    RefTableNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RefTableNameType fromValue(String v) {
        for (RefTableNameType c: RefTableNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
