//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:36 PM GMT 
//


package com.technobrain.trips.interfaces.registration.viewtaxpayer.message;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.technobrain.trips.interfaces.basetypes.message.ServiceResponseType;
import com.technobrain.trips.interfaces.registration.common.message.NonPeriodicAccountType;
import com.technobrain.trips.interfaces.registration.common.message.PeriodicAccountType;


/**
 * <p>Java class for AccountDetailsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountDetailsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://trips.technobrain.com/interfaces/basetypes/message}ServiceResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="PeriodicAccounts" type="{http://trips.technobrain.com/interfaces/registration/common/message}PeriodicAccountType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="NonPeriodicAccounts" type="{http://trips.technobrain.com/interfaces/registration/common/message}NonPeriodicAccountType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountDetailsResponse", propOrder = {
    "tin",
    "balance",
    "periodicAccounts",
    "nonPeriodicAccounts"
})
public class AccountDetailsResponse
    extends ServiceResponseType
{

    @XmlElement(required = true)
    protected String tin;
    @XmlElement(name = "Balance")
    protected BigDecimal balance;
    @XmlElement(name = "PeriodicAccounts")
    protected List<PeriodicAccountType> periodicAccounts;
    @XmlElement(name = "NonPeriodicAccounts")
    protected List<NonPeriodicAccountType> nonPeriodicAccounts;

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTin() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTin(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBalance(BigDecimal value) {
        this.balance = value;
    }

    /**
     * Gets the value of the periodicAccounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the periodicAccounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriodicAccounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodicAccountType }
     * 
     * 
     */
    public List<PeriodicAccountType> getPeriodicAccounts() {
        if (periodicAccounts == null) {
            periodicAccounts = new ArrayList<PeriodicAccountType>();
        }
        return this.periodicAccounts;
    }

    /**
     * Gets the value of the nonPeriodicAccounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonPeriodicAccounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNonPeriodicAccounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonPeriodicAccountType }
     * 
     * 
     */
    public List<NonPeriodicAccountType> getNonPeriodicAccounts() {
        if (nonPeriodicAccounts == null) {
            nonPeriodicAccounts = new ArrayList<NonPeriodicAccountType>();
        }
        return this.nonPeriodicAccounts;
    }

}
