//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:36 PM GMT 
//


package com.technobrain.trips.interfaces.registration.viewtaxpayer.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.technobrain.trips.interfaces.registration.viewtaxpayer.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrganisationDetails_QNAME = new QName("http://trips.technobrain.com/interfaces/viewtaxpayer/message", "OrganisationDetails");
    private final static QName _AccountDetailsRequest_QNAME = new QName("http://trips.technobrain.com/interfaces/viewtaxpayer/message", "AccountDetailsRequest");
    private final static QName _AccountDetailsResponse_QNAME = new QName("http://trips.technobrain.com/interfaces/viewtaxpayer/message", "AccountDetailsResponse");
    private final static QName _ReturnDetailsResponse_QNAME = new QName("http://trips.technobrain.com/interfaces/viewtaxpayer/message", "ReturnDetailsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.technobrain.trips.interfaces.registration.viewtaxpayer.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganisationDetailsType }
     * 
     */
    public OrganisationDetailsType createOrganisationDetailsType() {
        return new OrganisationDetailsType();
    }

    /**
     * Create an instance of {@link AccountDetailsRequest }
     * 
     */
    public AccountDetailsRequest createAccountDetailsRequest() {
        return new AccountDetailsRequest();
    }

    /**
     * Create an instance of {@link AccountDetailsResponse }
     * 
     */
    public AccountDetailsResponse createAccountDetailsResponse() {
        return new AccountDetailsResponse();
    }

    /**
     * Create an instance of {@link ReturnDetailsResponse }
     * 
     */
    public ReturnDetailsResponse createReturnDetailsResponse() {
        return new ReturnDetailsResponse();
    }

    /**
     * Create an instance of {@link TaxpayerDetailsType }
     * 
     */
    public TaxpayerDetailsType createTaxpayerDetailsType() {
        return new TaxpayerDetailsType();
    }

    /**
     * Create an instance of {@link TaxpayerStatusType }
     * 
     */
    public TaxpayerStatusType createTaxpayerStatusType() {
        return new TaxpayerStatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationDetailsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/interfaces/viewtaxpayer/message", name = "OrganisationDetails")
    public JAXBElement<OrganisationDetailsType> createOrganisationDetails(OrganisationDetailsType value) {
        return new JAXBElement<OrganisationDetailsType>(_OrganisationDetails_QNAME, OrganisationDetailsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountDetailsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/interfaces/viewtaxpayer/message", name = "AccountDetailsRequest")
    public JAXBElement<AccountDetailsRequest> createAccountDetailsRequest(AccountDetailsRequest value) {
        return new JAXBElement<AccountDetailsRequest>(_AccountDetailsRequest_QNAME, AccountDetailsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountDetailsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/interfaces/viewtaxpayer/message", name = "AccountDetailsResponse")
    public JAXBElement<AccountDetailsResponse> createAccountDetailsResponse(AccountDetailsResponse value) {
        return new JAXBElement<AccountDetailsResponse>(_AccountDetailsResponse_QNAME, AccountDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnDetailsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/interfaces/viewtaxpayer/message", name = "ReturnDetailsResponse")
    public JAXBElement<ReturnDetailsResponse> createReturnDetailsResponse(ReturnDetailsResponse value) {
        return new JAXBElement<ReturnDetailsResponse>(_ReturnDetailsResponse_QNAME, ReturnDetailsResponse.class, null, value);
    }

}
