//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:36 PM GMT 
//


package com.technobrain.trips.interfaces.registration.viewtaxpayer.message;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;


/**
 * <p>Java class for OrganisationDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrganisationDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://trips.technobrain.com/interfaces/viewtaxpayer/message}TaxpayerDetailsType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="organisationCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="organisation" type="{http://trips.technobrain.com/interfaces/basetypes/message}OrganisationNameType"/&gt;
 *         &lt;element name="tradingAs" type="{http://trips.technobrain.com/interfaces/basetypes/message}OrganisationNameType" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dateofIncorporation" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="accountYearEndDay" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="accountYearEndMonth" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="taxConsultantStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="website" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="assignedTaxOffice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="applicantTIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="firstName" type="{http://trips.technobrain.com/interfaces/basetypes/message}NameType" minOccurs="0"/&gt;
 *         &lt;element name="middleName" type="{http://trips.technobrain.com/interfaces/basetypes/message}NameType" minOccurs="0"/&gt;
 *         &lt;element name="lastName" type="{http://trips.technobrain.com/interfaces/basetypes/message}NameType" minOccurs="0"/&gt;
 *         &lt;element name="postalAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="contactDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrganisationDetailsType", propOrder = {
    "organisationCategory",
    "organisation",
    "tradingAs",
    "status",
    "dateofIncorporation",
    "accountYearEndDay",
    "accountYearEndMonth",
    "taxConsultantStatus",
    "website",
    "assignedTaxOffice",
    "applicantTIN",
    "firstName",
    "middleName",
    "lastName",
    "postalAddress",
    "contactDetails"
})
public class OrganisationDetailsType
    extends TaxpayerDetailsType
{

    @XmlElement(required = true)
    protected String organisationCategory;
    @XmlElement(required = true)
    protected String organisation;
    protected String tradingAs;
    @XmlElement(required = true)
    protected String status;
    @XmlSchemaType(name = "date")
    protected Calendar dateofIncorporation;
    protected BigInteger accountYearEndDay;
    protected BigInteger accountYearEndMonth;
    protected Boolean taxConsultantStatus;
    protected String website;
    protected String assignedTaxOffice;
    protected String applicantTIN;
    protected String firstName;
    protected String middleName;
    protected String lastName;
    protected String postalAddress;
    protected String contactDetails;

    /**
     * Gets the value of the organisationCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisationCategory() {
        return organisationCategory;
    }

    /**
     * Sets the value of the organisationCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisationCategory(String value) {
        this.organisationCategory = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganisation(String value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the tradingAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingAs() {
        return tradingAs;
    }

    /**
     * Sets the value of the tradingAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingAs(String value) {
        this.tradingAs = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dateofIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getDateofIncorporation() {
        return dateofIncorporation;
    }

    /**
     * Sets the value of the dateofIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setDateofIncorporation(Calendar value) {
        this.dateofIncorporation = value;
    }

    /**
     * Gets the value of the accountYearEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountYearEndDay() {
        return accountYearEndDay;
    }

    /**
     * Sets the value of the accountYearEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountYearEndDay(BigInteger value) {
        this.accountYearEndDay = value;
    }

    /**
     * Gets the value of the accountYearEndMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountYearEndMonth() {
        return accountYearEndMonth;
    }

    /**
     * Sets the value of the accountYearEndMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountYearEndMonth(BigInteger value) {
        this.accountYearEndMonth = value;
    }

    /**
     * Gets the value of the taxConsultantStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTaxConsultantStatus() {
        return taxConsultantStatus;
    }

    /**
     * Sets the value of the taxConsultantStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTaxConsultantStatus(Boolean value) {
        this.taxConsultantStatus = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the assignedTaxOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedTaxOffice() {
        return assignedTaxOffice;
    }

    /**
     * Sets the value of the assignedTaxOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedTaxOffice(String value) {
        this.assignedTaxOffice = value;
    }

    /**
     * Gets the value of the applicantTIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicantTIN() {
        return applicantTIN;
    }

    /**
     * Sets the value of the applicantTIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicantTIN(String value) {
        this.applicantTIN = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the postalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalAddress() {
        return postalAddress;
    }

    /**
     * Sets the value of the postalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalAddress(String value) {
        this.postalAddress = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactDetails(String value) {
        this.contactDetails = value;
    }

}
