//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 06:04:36 PM GMT 
//


package com.technobrain.trips.interfaces.registration.viewtaxpayer.message;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.technobrain.trips.interfaces.basetypes.message.ServiceResponseType;
import com.technobrain.trips.interfaces.registration.common.message.ReturnDocumentDetailsType;


/**
 * <p>Java class for ReturnDetailsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReturnDetailsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://trips.technobrain.com/interfaces/basetypes/message}ServiceResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ReturnDocumentDetails" type="{http://trips.technobrain.com/interfaces/registration/common/message}ReturnDocumentDetailsType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReturnDetailsResponse", propOrder = {
    "tin",
    "returnDocumentDetails"
})
public class ReturnDetailsResponse
    extends ServiceResponseType
{

    protected String tin;
    @XmlElement(name = "ReturnDocumentDetails")
    protected List<ReturnDocumentDetailsType> returnDocumentDetails;

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTin() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTin(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the returnDocumentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the returnDocumentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturnDocumentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReturnDocumentDetailsType }
     * 
     * 
     */
    public List<ReturnDocumentDetailsType> getReturnDocumentDetails() {
        if (returnDocumentDetails == null) {
            returnDocumentDetails = new ArrayList<ReturnDocumentDetailsType>();
        }
        return this.returnDocumentDetails;
    }

}
