/**
 * PublicReportService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.oracle.xmlns.oxp.service.PublicReportService;

public interface PublicReportService extends java.rmi.Remote {
    public java.lang.String login(java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException;
    public boolean logout(java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ParamNameValue[] getReportParameters(com.oracle.xmlns.oxp.service.PublicReportService.ReportRequest reportRequest, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String createReport(java.lang.String reportName, java.lang.String folderAbsolutePathURL, java.lang.String templateFileName, byte[] templateData, java.lang.String XLIFFFileName, byte[] XLIFFData, boolean updateFlag, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteReport(java.lang.String reportAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean validateLogin(java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException;
    public java.lang.String getSecurityModel() throws java.rmi.RemoteException;
    public int getBIPHTTPSessionInterval() throws java.rmi.RemoteException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ReportResponse runReport(com.oracle.xmlns.oxp.service.PublicReportService.ReportRequest reportRequest, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ReportResponse runReportInSession(com.oracle.xmlns.oxp.service.PublicReportService.ReportRequest reportRequest, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ReportDefinition getReportDefinition(java.lang.String reportAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ReportDefinition getReportDefinitionInSession(java.lang.String reportAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ParamNameValue[] getReportParametersInSession(com.oracle.xmlns.oxp.service.PublicReportService.ReportRequest reportRequest, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ItemData[] getFolderContents(java.lang.String folderAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ItemData[] getFolderContentsInSession(java.lang.String folderAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String scheduleReport(com.oracle.xmlns.oxp.service.PublicReportService.ScheduleRequest scheduleRequest, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String scheduleReportInSession(com.oracle.xmlns.oxp.service.PublicReportService.ScheduleRequest scheduleRequest, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean hasReportAccess(java.lang.String reportAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean hasReportAccessInSession(java.lang.String reportAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobStatus getScheduledReportStatus(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobStatus getScheduledReportStatusInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobStatus[] getListOfScheduledReportsStatusInSession(java.lang.String[] scheduledJobIDs, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobInfo[] getScheduledReportInfo(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password, java.lang.String viewByFilter) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobInfo[] getScheduledReportInfoInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken, java.lang.String userID, java.lang.String viewByFilter) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobHistoryInfo[] getScheduledReportHistoryInfo(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password, java.lang.String viewByFilter, boolean bDownloadReport) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public com.oracle.xmlns.oxp.service.PublicReportService.JobHistoryInfo[] getScheduledReportHistoryInfoInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken, java.lang.String userID, java.lang.String viewByFilter, boolean bDownloadReport) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean suspendScheduledReport(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean suspendScheduledReportInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean resumeScheduledReport(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean resumeScheduledReportInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteScheduledReport(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteScheduledReportInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteScheduledReportHistory(java.lang.String scheduledJobID, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteScheduledReportHistoryInSession(java.lang.String scheduledJobID, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String createReportInSession(java.lang.String reportName, java.lang.String folderAbsolutePathURL, java.lang.String templateFileName, byte[] templateData, java.lang.String XLIFFFileName, byte[] XLIFFData, boolean updateFlag, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean updateReportDefinition(java.lang.String reportAbsPath, com.oracle.xmlns.oxp.service.PublicReportService.ReportDefinition newReportDefn, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean updateReportDefinitionInSession(java.lang.String reportAbsPath, com.oracle.xmlns.oxp.service.PublicReportService.ReportDefinition newReportDefn, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String createReportFolder(java.lang.String folderAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String createReportFolderInSession(java.lang.String folderAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean uploadTemplateForReport(java.lang.String reportAbsolutePath, java.lang.String templateFileName, byte[] templateData, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean uploadTemplateForReportInSession(java.lang.String reportAbsolutePath, java.lang.String templateFileName, byte[] templateData, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean removeTemplateForReport(java.lang.String reportAbsolutePath, java.lang.String templateFileName, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean removeTemplateForReportInSession(java.lang.String reportAbsolutePath, java.lang.String templateFileName, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String uploadReportDataChunk(java.lang.String fileID, byte[] reportDataChunk) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException;
    public com.oracle.xmlns.oxp.service.PublicReportService.ReportDataChunk downloadReportDataChunk(java.lang.String fileID, int beginIdx, int size) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException;
    public java.lang.String uploadReport(java.lang.String reportName, java.lang.String folderAbsolutePathURL, byte[] reportZippedData, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public java.lang.String uploadReportInSession(java.lang.String reportName, java.lang.String folderAbsolutePathURL, byte[] reportZippedData, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteReportInSession(java.lang.String reportAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteFolder(java.lang.String folderAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public boolean deleteFolderInSession(java.lang.String folderAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public byte[] downloadReport(java.lang.String reportAbsolutePath, java.lang.String userID, java.lang.String password) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
    public byte[] downloadReportInSession(java.lang.String reportAbsolutePath, java.lang.String bipSessionToken) throws java.rmi.RemoteException, com.oracle.xmlns.oxp.service.PublicReportService.AccessDeniedException, com.oracle.xmlns.oxp.service.PublicReportService.OperationFailedException, com.oracle.xmlns.oxp.service.PublicReportService.InvalidParametersException;
}
