//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 09:53:06 AM GMT 
//


package com.technobrain.trips.entityandregimeaccounting.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.technobrain.trips.entityandregimeaccounting.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AccountType_QNAME = new QName("http://trips.technobrain.com/entityandregimeaccounting/message", "AccountType");
    private final static QName _PeriodType_QNAME = new QName("http://trips.technobrain.com/entityandregimeaccounting/message", "PeriodType");
    private final static QName _RevenueAccountType_QNAME = new QName("http://trips.technobrain.com/entityandregimeaccounting/message", "RevenueAccountType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.technobrain.trips.entityandregimeaccounting.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RevenueAccountType }
     * 
     */
    public RevenueAccountType createRevenueAccountType() {
        return new RevenueAccountType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/entityandregimeaccounting/message", name = "AccountType")
    public JAXBElement<AccountType> createAccountType(AccountType value) {
        return new JAXBElement<AccountType>(_AccountType_QNAME, AccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/entityandregimeaccounting/message", name = "PeriodType")
    public JAXBElement<PeriodType> createPeriodType(PeriodType value) {
        return new JAXBElement<PeriodType>(_PeriodType_QNAME, PeriodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevenueAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/entityandregimeaccounting/message", name = "RevenueAccountType")
    public JAXBElement<RevenueAccountType> createRevenueAccountType(RevenueAccountType value) {
        return new JAXBElement<RevenueAccountType>(_RevenueAccountType_QNAME, RevenueAccountType.class, null, value);
    }

}
