//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 09:53:06 AM GMT 
//


package com.technobrain.trips.entityandregimeaccounting.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;
import com.technobrain.trips.core.message.InputType;


/**
 * <p>Java class for PeriodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeriodType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://trips.technobrain.com/core/message}InputType">
 *       &lt;sequence>
 *         &lt;element name="PaymentDue" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PeriodEnd" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PeriodNo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PeriodStart" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PeriodYear" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RegimeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReturnDue" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="RegimeAccountId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="RevenueType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RevenueReturnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="FilingFrequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OverrideNumberOfPeriods" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AccountEndMonth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AccountEndDay" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FiscalIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeriodType", propOrder = {
    "paymentDue",
    "periodEnd",
    "periodNo",
    "periodStart",
    "periodYear",
    "regimeType",
    "returnDue",
    "regimeAccountId",
    "revenueType",
    "revenueReturnType",
    "registrationDate",
    "filingFrequency",
    "overrideNumberOfPeriods",
    "accountEndMonth",
    "accountEndDay",
    "fiscalIndicator"
})
public class PeriodType
    extends InputType
{

    @XmlElement(name = "PaymentDue")
    @XmlSchemaType(name = "date")
    protected Calendar paymentDue;
    @XmlElement(name = "PeriodEnd")
    @XmlSchemaType(name = "date")
    protected Calendar periodEnd;
    @XmlElement(name = "PeriodNo")
    protected Integer periodNo;
    @XmlElement(name = "PeriodStart")
    @XmlSchemaType(name = "date")
    protected Calendar periodStart;
    @XmlElement(name = "PeriodYear")
    protected Integer periodYear;
    @XmlElement(name = "RegimeType")
    protected String regimeType;
    @XmlElement(name = "ReturnDue")
    @XmlSchemaType(name = "date")
    protected Calendar returnDue;
    @XmlElement(name = "RegimeAccountId")
    protected Long regimeAccountId;
    @XmlElement(name = "RevenueType")
    protected String revenueType;
    @XmlElement(name = "RevenueReturnType")
    protected String revenueReturnType;
    @XmlElement(name = "RegistrationDate")
    @XmlSchemaType(name = "date")
    protected Calendar registrationDate;
    @XmlElement(name = "FilingFrequency")
    protected String filingFrequency;
    @XmlElement(name = "OverrideNumberOfPeriods")
    protected Integer overrideNumberOfPeriods;
    @XmlElement(name = "AccountEndMonth")
    protected Integer accountEndMonth;
    @XmlElement(name = "AccountEndDay")
    protected Integer accountEndDay;
    @XmlElement(name = "FiscalIndicator")
    protected Boolean fiscalIndicator;

    /**
     * Gets the value of the paymentDue property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getPaymentDue() {
        return paymentDue;
    }

    /**
     * Sets the value of the paymentDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setPaymentDue(Calendar value) {
        this.paymentDue = value;
    }

    /**
     * Gets the value of the periodEnd property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getPeriodEnd() {
        return periodEnd;
    }

    /**
     * Sets the value of the periodEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setPeriodEnd(Calendar value) {
        this.periodEnd = value;
    }

    /**
     * Gets the value of the periodNo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPeriodNo() {
        return periodNo;
    }

    /**
     * Sets the value of the periodNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPeriodNo(Integer value) {
        this.periodNo = value;
    }

    /**
     * Gets the value of the periodStart property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getPeriodStart() {
        return periodStart;
    }

    /**
     * Sets the value of the periodStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setPeriodStart(Calendar value) {
        this.periodStart = value;
    }

    /**
     * Gets the value of the periodYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPeriodYear() {
        return periodYear;
    }

    /**
     * Sets the value of the periodYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPeriodYear(Integer value) {
        this.periodYear = value;
    }

    /**
     * Gets the value of the regimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegimeType() {
        return regimeType;
    }

    /**
     * Sets the value of the regimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegimeType(String value) {
        this.regimeType = value;
    }

    /**
     * Gets the value of the returnDue property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getReturnDue() {
        return returnDue;
    }

    /**
     * Sets the value of the returnDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setReturnDue(Calendar value) {
        this.returnDue = value;
    }

    /**
     * Gets the value of the regimeAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRegimeAccountId() {
        return regimeAccountId;
    }

    /**
     * Sets the value of the regimeAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRegimeAccountId(Long value) {
        this.regimeAccountId = value;
    }

    /**
     * Gets the value of the revenueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueType() {
        return revenueType;
    }

    /**
     * Sets the value of the revenueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueType(String value) {
        this.revenueType = value;
    }

    /**
     * Gets the value of the revenueReturnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueReturnType() {
        return revenueReturnType;
    }

    /**
     * Sets the value of the revenueReturnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueReturnType(String value) {
        this.revenueReturnType = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setRegistrationDate(Calendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the filingFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingFrequency() {
        return filingFrequency;
    }

    /**
     * Sets the value of the filingFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingFrequency(String value) {
        this.filingFrequency = value;
    }

    /**
     * Gets the value of the overrideNumberOfPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverrideNumberOfPeriods() {
        return overrideNumberOfPeriods;
    }

    /**
     * Sets the value of the overrideNumberOfPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverrideNumberOfPeriods(Integer value) {
        this.overrideNumberOfPeriods = value;
    }

    /**
     * Gets the value of the accountEndMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountEndMonth() {
        return accountEndMonth;
    }

    /**
     * Sets the value of the accountEndMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountEndMonth(Integer value) {
        this.accountEndMonth = value;
    }

    /**
     * Gets the value of the accountEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountEndDay() {
        return accountEndDay;
    }

    /**
     * Sets the value of the accountEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountEndDay(Integer value) {
        this.accountEndDay = value;
    }

    /**
     * Gets the value of the fiscalIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFiscalIndicator() {
        return fiscalIndicator;
    }

    /**
     * Sets the value of the fiscalIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFiscalIndicator(Boolean value) {
        this.fiscalIndicator = value;
    }

}
