package com.technobrain.trips.core.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
* TechnoBrain 2015
* <br>
* A Reference Number is a unique number that is specific to an entity. This number is shown to the user to represent the entity. <br>
* <br> It is generated by the ReferenceNumberGenerator which generates the reference number.
*/

@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface ReferenceNumber {
    
    java.lang.String sql();
    java.lang.String format();
}