//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.09 at 02:48:09 PM BST 
//


package com.technobrain.trips.egif;

import java.io.Serializable;

public class RegisterTaxpayerServiceResponse implements Serializable{


    protected GcmsOutputType _return;

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link GcmsOutputType }
     *     
     */
    public GcmsOutputType getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link GcmsOutputType }
     *     
     */
    public void setReturn(GcmsOutputType value) {
        this._return = value;
    }

}
