//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 10:51:10 AM GMT 
//


package com.technobrain.trips.interfaces.registration.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.technobrain.trips.interfaces.registration.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegisterOrganisationResponse_QNAME = new QName("http://trips.technobrain.com/interfaces/registration/message", "RegisterOrganisationResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.technobrain.trips.interfaces.registration.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterOrganisationResponse }
     * 
     */
    public RegisterOrganisationResponse createRegisterOrganisationResponse() {
        return new RegisterOrganisationResponse();
    }

    /**
     * Create an instance of {@link RegisterOrganisation }
     * 
     */
    public RegisterOrganisation createRegisterOrganisation() {
        return new RegisterOrganisation();
    }

    /**
     * Create an instance of {@link OrgReg }
     * 
     */
    public OrgReg createOrgReg() {
        return new OrgReg();
    }

    /**
     * Create an instance of {@link OrgRegOutput }
     * 
     */
    public OrgRegOutput createOrgRegOutput() {
        return new OrgRegOutput();
    }

    /**
     * Create an instance of {@link TaxpayerStatusType }
     * 
     */
    public TaxpayerStatusType createTaxpayerStatusType() {
        return new TaxpayerStatusType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterOrganisationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://trips.technobrain.com/interfaces/registration/message", name = "RegisterOrganisationResponse")
    public JAXBElement<RegisterOrganisationResponse> createRegisterOrganisationResponse(RegisterOrganisationResponse value) {
        return new JAXBElement<RegisterOrganisationResponse>(_RegisterOrganisationResponse_QNAME, RegisterOrganisationResponse.class, null, value);
    }

}
