//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 10:51:10 AM GMT 
//


package com.technobrain.trips.interfaces.registration.message;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.technobrain.trips.interfaces.registration.common.message.AddressInfoType;
import com.technobrain.trips.interfaces.registration.common.message.ContactMethodType;
import com.technobrain.trips.interfaces.registration.common.message.Outcomes;
import com.technobrain.trips.interfaces.registration.common.message.RegStatus;
import java.util.Calendar;


/**
 * <p>Java class for OrgReg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgReg"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="accountYearEndDay" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="accoutYearEndMonth" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="businessName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="commencementDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="legalStatusType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="incorporationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="isicCodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="office" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="orgContactDetails" type="{http://trips.technobrain.com/interfaces/registration/common/message}ContactMethodType" minOccurs="0"/&gt;
 *         &lt;element name="previousTin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="principalBusinessAddress" type="{http://trips.technobrain.com/interfaces/registration/common/message}AddressInfoType" minOccurs="0"/&gt;
 *         &lt;element name="registrationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="rgdNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="portalUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="registrationStatus" type="{http://trips.technobrain.com/interfaces/registration/common/message}RegStatus" minOccurs="0"/&gt;
 *         &lt;element name="outcome" type="{http://trips.technobrain.com/interfaces/registration/common/message}Outcomes" minOccurs="0"/&gt;
 *         &lt;element name="referenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgReg", propOrder = {
    "accountYearEndDay",
    "accoutYearEndMonth",
    "businessName",
    "commencementDate",
    "legalStatusType",
    "incorporationDate",
    "isicCodes",
    "office",
    "orgContactDetails",
    "previousTin",
    "principalBusinessAddress",
    "registrationDate",
    "rgdNo",
    "portalUserName",
    "registrationStatus",
    "outcome",
    "referenceNumber"
})
public class OrgReg {

    @XmlElement(required = true)
    protected BigInteger accountYearEndDay;
    @XmlElement(required = true)
    protected BigInteger accoutYearEndMonth;
    protected String businessName;
    @XmlSchemaType(name = "dateTime")
    protected Calendar commencementDate;
    protected String legalStatusType;
    @XmlSchemaType(name = "dateTime")
    protected Calendar incorporationDate;
    protected String isicCodes;
    protected String office;
    protected ContactMethodType orgContactDetails;
    protected String previousTin;
    protected AddressInfoType principalBusinessAddress;
    @XmlSchemaType(name = "dateTime")
    protected Calendar registrationDate;
    protected String rgdNo;
    protected String portalUserName;
    @XmlSchemaType(name = "string")
    protected RegStatus registrationStatus;
    @XmlSchemaType(name = "string")
    protected Outcomes outcome;
    protected String referenceNumber;

    /**
     * Gets the value of the accountYearEndDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccountYearEndDay() {
        return accountYearEndDay;
    }

    /**
     * Sets the value of the accountYearEndDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccountYearEndDay(BigInteger value) {
        this.accountYearEndDay = value;
    }

    /**
     * Gets the value of the accoutYearEndMonth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccoutYearEndMonth() {
        return accoutYearEndMonth;
    }

    /**
     * Sets the value of the accoutYearEndMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccoutYearEndMonth(BigInteger value) {
        this.accoutYearEndMonth = value;
    }

    /**
     * Gets the value of the businessName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * Sets the value of the businessName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessName(String value) {
        this.businessName = value;
    }

    /**
     * Gets the value of the commencementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getCommencementDate() {
        return commencementDate;
    }

    /**
     * Sets the value of the commencementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommencementDate(Calendar value) {
        this.commencementDate = value;
    }

    /**
     * Gets the value of the legalStatusType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatusType() {
        return legalStatusType;
    }

    /**
     * Sets the value of the legalStatusType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatusType(String value) {
        this.legalStatusType = value;
    }

    /**
     * Gets the value of the incorporationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getIncorporationDate() {
        return incorporationDate;
    }

    /**
     * Sets the value of the incorporationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIncorporationDate(Calendar value) {
        this.incorporationDate = value;
    }

    /**
     * Gets the value of the isicCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsicCodes() {
        return isicCodes;
    }

    /**
     * Sets the value of the isicCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsicCodes(String value) {
        this.isicCodes = value;
    }

    /**
     * Gets the value of the office property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffice() {
        return office;
    }

    /**
     * Sets the value of the office property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffice(String value) {
        this.office = value;
    }

    /**
     * Gets the value of the orgContactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactMethodType }
     *     
     */
    public ContactMethodType getOrgContactDetails() {
        return orgContactDetails;
    }

    /**
     * Sets the value of the orgContactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactMethodType }
     *     
     */
    public void setOrgContactDetails(ContactMethodType value) {
        this.orgContactDetails = value;
    }

    /**
     * Gets the value of the previousTin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousTin() {
        return previousTin;
    }

    /**
     * Sets the value of the previousTin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousTin(String value) {
        this.previousTin = value;
    }

    /**
     * Gets the value of the principalBusinessAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressInfoType }
     *     
     */
    public AddressInfoType getPrincipalBusinessAddress() {
        return principalBusinessAddress;
    }

    /**
     * Sets the value of the principalBusinessAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressInfoType }
     *     
     */
    public void setPrincipalBusinessAddress(AddressInfoType value) {
        this.principalBusinessAddress = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Calendar getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRegistrationDate(Calendar value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the rgdNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRgdNo() {
        return rgdNo;
    }

    /**
     * Sets the value of the rgdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRgdNo(String value) {
        this.rgdNo = value;
    }

    /**
     * Gets the value of the portalUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalUserName() {
        return portalUserName;
    }

    /**
     * Sets the value of the portalUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalUserName(String value) {
        this.portalUserName = value;
    }

    /**
     * Gets the value of the registrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RegStatus }
     *     
     */
    public RegStatus getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * Sets the value of the registrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegStatus }
     *     
     */
    public void setRegistrationStatus(RegStatus value) {
        this.registrationStatus = value;
    }

    /**
     * Gets the value of the outcome property.
     * 
     * @return
     *     possible object is
     *     {@link Outcomes }
     *     
     */
    public Outcomes getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outcomes }
     *     
     */
    public void setOutcome(Outcomes value) {
        this.outcome = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

}
