//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.12-b141219.1637 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.02 at 10:51:10 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://trips.technobrain.com/interfaces/registration/message")
package com.technobrain.trips.interfaces.registration.message;
